# Generated by Django 5.2.1 on 2025-05-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('chai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniproject.chaivarirty')),
            ],
        ),
    ]
