# Generated by Django 5.2.1 on 2025-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0003_chaireview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chaivarirty',
            name='ingredients',
            field=models.ManyToManyField(related_name='chai_varieties', to='miniproject.ingredient'),
        ),
    ]
